# Generated by Django 2.0 on 2017-12-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/static/book.jpg', upload_to=''),
        ),
    ]
