# Generated by Django 2.0 on 2017-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0003_auto_20171223_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/static/default.jpg', upload_to='static/images'),
        ),
    ]
