# Generated by Django 2.0 on 2017-12-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0004_auto_20171223_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='static/images'),
        ),
    ]
