# Generated by Django 2.0 on 2017-12-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0005_auto_20171223_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='alpha_book/static/images/default.jpg', upload_to='alpha_book/static/images'),
        ),
    ]
