# Generated by Django 2.0 on 2017-12-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0006_auto_20171223_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='alpha_book/static/images'),
        ),
    ]
