# Generated by Django 2.0 on 2017-12-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_book', '0008_auto_20171223_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/book.jpg', upload_to='static/images'),
        ),
    ]
